description: This is a template researchers can walk away with and create their own Portfolio.
datelastupdated: 25 Nov 2021
fullnameofperson: Yana Salchak
selfIdentification: PhD Candidate | Biomedical Engineering
colour1: "  #23395B"  # sidebar background 
colour2: " #f5820e"  # colour of name and desc
colour3: " #f5820e"  # colour of Menu links
colour4: "  #EAF2F8 " # trying to be background colour - still experimenting 
colour5: " #EAF2F8" # menu link colour when hover
